export EDITOR="nvim"
export TERMINAL="alacritty"
export FM="nnn"
export PYENV_ROOT="$HOME/.pyenv"
export KEYTIMEOUT=1
# pager
export PAGER="nvimpager"
export MANPAGER='nvim +Man!'
export GIT_PAGER="nvimpager"
# ibus
export GTK_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export SCRIPTS_HOME="$HOME/.local/scripts"
export XDG_STATE_HOME="$HOME/.local/state"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/"node_repl_history
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export SSB_HOME="$XDG_DATA_HOME"/zoom
export CARGO_HOME="$XDG_DATA_HOME"/cargo
# mozilla
export MOZ_USE_XINPUT2=1
export MOZ_ENABLE_WAYLAND=1
# qt
export QT_QPA_PLATFORMTHEME=gtk3
export QT_STYLE_OVERRIDE=kvantum
# java
export _JAVA_AWT_WM_NONREPARENTING=1
export CHROME_EXECUTABLE=/bin/chromium
# X11
export WINIT_X11_SCALE_FACTOR=1

# lang
export LANG="en_US.UTF-8"
